//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CapaDatos
{
    using System;
    using System.Collections.Generic;
    
    public partial class GNB_PRODUCTOS
    {
        public int ID_PRODUCTOS { get; set; }
        public int SKU { get; set; }
        public decimal AMMOUNT { get; set; }
        public string CURRENCY { get; set; }
    }
}
